/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import controller.CadastroUniversidadeController;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Jhonatan Borges
 */
public class CadastroUniversidade extends javax.swing.JFrame {
    
    
    private final CadastroUniversidadeController controller;
    /**
     * Creates new form CadastroUniversidade
     */
    public CadastroUniversidade() {
        initComponents();
        controller = new CadastroUniversidadeController(this);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlUniao = new javax.swing.JPanel();
        pnlTitulo = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblCorTitulo = new javax.swing.JLabel();
        pnlInformacoesUniversidade = new javax.swing.JPanel();
        lblNomeUniversidade = new javax.swing.JLabel();
        lblEstado = new javax.swing.JLabel();
        lblCampus = new javax.swing.JLabel();
        txtNomeUniversidade = new javax.swing.JTextField();
        cmbEstado = new javax.swing.JComboBox<>();
        txtCampus = new javax.swing.JTextField();
        bntSalvar = new javax.swing.JButton();
        bntLimpar = new javax.swing.JButton();
        bntVoltar2 = new javax.swing.JButton();
        lblBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Universidade");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlUniao.setBackground(new java.awt.Color(255, 255, 255));
        pnlUniao.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlTitulo.setBackground(new java.awt.Color(255, 153, 0));
        pnlTitulo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnlTitulo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitulo.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lblTitulo.setText("Cadastro de Universidade");
        pnlTitulo.add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, -1, -1));

        lblCorTitulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/grey.png"))); // NOI18N
        lblCorTitulo.setText("jLabel6");
        pnlTitulo.add(lblCorTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 70));

        pnlUniao.add(pnlTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        pnlInformacoesUniversidade.setBackground(new java.awt.Color(255, 255, 255));
        pnlInformacoesUniversidade.setBorder(javax.swing.BorderFactory.createTitledBorder("Informações da Universidade"));
        pnlInformacoesUniversidade.setToolTipText("");

        lblNomeUniversidade.setText("Nome:");

        lblEstado.setText("Estado:");

        lblCampus.setText("Campus:");

        cmbEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));

        javax.swing.GroupLayout pnlInformacoesUniversidadeLayout = new javax.swing.GroupLayout(pnlInformacoesUniversidade);
        pnlInformacoesUniversidade.setLayout(pnlInformacoesUniversidadeLayout);
        pnlInformacoesUniversidadeLayout.setHorizontalGroup(
            pnlInformacoesUniversidadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInformacoesUniversidadeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlInformacoesUniversidadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlInformacoesUniversidadeLayout.createSequentialGroup()
                        .addComponent(txtCampus, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnlInformacoesUniversidadeLayout.createSequentialGroup()
                        .addGroup(pnlInformacoesUniversidadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNomeUniversidade)
                            .addComponent(txtNomeUniversidade, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnlInformacoesUniversidadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblEstado)
                            .addComponent(cmbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(68, 68, 68))
                    .addGroup(pnlInformacoesUniversidadeLayout.createSequentialGroup()
                        .addComponent(lblCampus)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        pnlInformacoesUniversidadeLayout.setVerticalGroup(
            pnlInformacoesUniversidadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInformacoesUniversidadeLayout.createSequentialGroup()
                .addGroup(pnlInformacoesUniversidadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNomeUniversidade)
                    .addComponent(lblEstado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlInformacoesUniversidadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNomeUniversidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCampus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCampus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlUniao.add(pnlInformacoesUniversidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 650, -1));

        bntSalvar.setBackground(new java.awt.Color(255, 255, 255));
        bntSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/salvar.png"))); // NOI18N
        bntSalvar.setText("Salvar");
        bntSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntSalvarActionPerformed(evt);
            }
        });
        pnlUniao.add(bntSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, -1, -1));

        bntLimpar.setBackground(new java.awt.Color(255, 255, 255));
        bntLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/limpar .png"))); // NOI18N
        bntLimpar.setText("Limpar");
        bntLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntLimparActionPerformed(evt);
            }
        });
        pnlUniao.add(bntLimpar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 220, -1, -1));

        bntVoltar2.setBackground(new java.awt.Color(255, 255, 255));
        bntVoltar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/voltar.png"))); // NOI18N
        bntVoltar2.setText("Voltar");
        bntVoltar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntVoltar2ActionPerformed(evt);
            }
        });
        pnlUniao.add(bntVoltar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 220, -1, -1));

        getContentPane().add(pnlUniao, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 670, 260));

        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/background-2.png"))); // NOI18N
        getContentPane().add(lblBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, 280));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bntSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntSalvarActionPerformed

        /* Exibe alerta caso algum campo do formulario esteja vazio, se não exibir
        salva o dado */
        if(!(controller.exibirAlertarCampos())){
            //Salva os dados no banco de dados
            controller.salvarCadastro();            
        }

    }//GEN-LAST:event_bntSalvarActionPerformed

    private void bntLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntLimparActionPerformed
        //Método que limpa os campos
        controller.limparCampos();
    }//GEN-LAST:event_bntLimparActionPerformed

    private void bntVoltar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntVoltar2ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_bntVoltar2ActionPerformed

    
    //Getters e Setters
    
     public JTextField getTxtNomeUniversidade(){
        return txtNomeUniversidade;
    }
    public JComboBox<String> getCmbEstado() {
        return cmbEstado;
    }
    
    public JTextField getTxtCampus(){
        return txtCampus;
    }    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroUniversidade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroUniversidade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroUniversidade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroUniversidade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroUniversidade().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntLimpar;
    private javax.swing.JButton bntSalvar;
    private javax.swing.JButton bntVoltar2;
    private javax.swing.JComboBox<String> cmbEstado;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblCampus;
    private javax.swing.JLabel lblCorTitulo;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblNomeUniversidade;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel pnlInformacoesUniversidade;
    private javax.swing.JPanel pnlTitulo;
    private javax.swing.JPanel pnlUniao;
    private javax.swing.JTextField txtCampus;
    private javax.swing.JTextField txtNomeUniversidade;
    // End of variables declaration//GEN-END:variables

   
    
    
    
}
