
package telas;


import java.awt.Toolkit;
import java.io.IOException;
import java.net.URISyntaxException;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Jhonatan Borges
 */
public class Principal extends javax.swing.JFrame {
    
    /**
     * Creates new form PrincipalFinal
     */
    public Principal() {
        initComponents();
        setLocationRelativeTo(null);
        
        
        
        //bntCadastroAluno.setBackground(Color.yellow);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        bntProfessor = new javax.swing.JLabel();
        bntAluno = new javax.swing.JLabel();
        bntUniversidade = new javax.swing.JLabel();
        bntTurma = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        LOGO = new javax.swing.JLabel();
        lblCINCUN = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        background = new javax.swing.JLabel();
        mnbLogin = new javax.swing.JMenuBar();
        mnAjuda = new javax.swing.JMenu();
        mnSobre = new javax.swing.JMenu();
        mnSair = new javax.swing.JMenu();
        mntSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CyberTop - Principal");
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/imagens/icone.png")).getImage());
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 6));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bntProfessor.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        bntProfessor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/teacher.png"))); // NOI18N
        bntProfessor.setText("Professor");
        bntProfessor.setToolTipText("Gerenciar professor");
        bntProfessor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bntProfessorMouseClicked(evt);
            }
        });
        jPanel1.add(bntProfessor, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        bntAluno.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        bntAluno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/student.png"))); // NOI18N
        bntAluno.setText("Aluno");
        bntAluno.setToolTipText("Gerenciar aluno");
        bntAluno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bntAlunoMouseClicked(evt);
            }
        });
        jPanel1.add(bntAluno, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, -1, -1));

        bntUniversidade.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        bntUniversidade.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/school.png"))); // NOI18N
        bntUniversidade.setText("Universidade");
        bntUniversidade.setToolTipText("Gerenciar universidade");
        bntUniversidade.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bntUniversidadeMouseClicked(evt);
            }
        });
        jPanel1.add(bntUniversidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, -1, -1));

        bntTurma.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        bntTurma.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/classroom.png"))); // NOI18N
        bntTurma.setText("Turma");
        bntTurma.setToolTipText("Gerenciar turma");
        bntTurma.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bntTurmaMouseClicked(evt);
            }
        });
        jPanel1.add(bntTurma, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/grey.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 181));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, 430, 180));

        LOGO.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        LOGO.setForeground(new java.awt.Color(255, 255, 255));
        LOGO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/LOGO.jpg"))); // NOI18N
        LOGO.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LOGOMouseClicked(evt);
            }
        });
        getContentPane().add(LOGO, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, -1, 100));

        lblCINCUN.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 14)); // NOI18N
        lblCINCUN.setForeground(new java.awt.Color(255, 255, 255));
        lblCINCUN.setText("  Aqui você garante sua aprovação");
        getContentPane().add(lblCINCUN, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, 240, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/sistema-de-gerenciamento-de-conteudo.png"))); // NOI18N
        jLabel3.setText("Gerenciar");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 180, -1, -1));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/background-2.png"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 410));

        mnAjuda.setText("Ajuda");
        mnAjuda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnAjudaMouseClicked(evt);
            }
        });
        mnAjuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnAjudaActionPerformed(evt);
            }
        });
        mnbLogin.add(mnAjuda);

        mnSobre.setText("Sobre");
        mnSobre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnSobreMouseClicked(evt);
            }
        });
        mnbLogin.add(mnSobre);

        mnSair.setText("Sair");
        mnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnSairActionPerformed(evt);
            }
        });

        mntSair.setText("Desejo realmente sair!");
        mntSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mntSairActionPerformed(evt);
            }
        });
        mnSair.add(mntSair);

        mnbLogin.add(mnSair);

        setJMenuBar(mnbLogin);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mntSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mntSairActionPerformed
        // Encerra a execução
        System.exit(0);
    }//GEN-LAST:event_mntSairActionPerformed

    private void mnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnSairActionPerformed

    }//GEN-LAST:event_mnSairActionPerformed

    private void mnAjudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnAjudaActionPerformed

        
    }//GEN-LAST:event_mnAjudaActionPerformed

    private void LOGOMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LOGOMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_LOGOMouseClicked

    private void bntProfessorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bntProfessorMouseClicked
        try {
            // TODO add your handling code here:
            new GerenciarProfessor().setVisible(true);
        } catch (SQLException | ParseException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_bntProfessorMouseClicked

    private void bntTurmaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bntTurmaMouseClicked
        try {
            // TODO add your handling code here:
            new GerenciarTurma().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_bntTurmaMouseClicked

    private void bntAlunoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bntAlunoMouseClicked
        // TODO add your handling code here:
        new GerenciarAluno().setVisible(true);
    }//GEN-LAST:event_bntAlunoMouseClicked

    private void bntUniversidadeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bntUniversidadeMouseClicked
        try {
            // TODO add your handling code here:
            new GerenciarUniversidade().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_bntUniversidadeMouseClicked

    private void mnAjudaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnAjudaMouseClicked
        try {
            // TODO add your handling code here:

            java.awt.Desktop.getDesktop().browse( new java.net.URI( "https://www.facebook.com/Suporte-CyberTop-104782918137245" ) );
        } catch (URISyntaxException | IOException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_mnAjudaMouseClicked

    private void mnSobreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnSobreMouseClicked
        try {
            // TODO add your handling code here:

            java.awt.Desktop.getDesktop().browse( new java.net.URI( "https://www.facebook.com/Suporte-CyberTop-104782918137245" ) );
        } catch (URISyntaxException | IOException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_mnSobreMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LOGO;
    private javax.swing.JLabel background;
    private javax.swing.JLabel bntAluno;
    private javax.swing.JLabel bntProfessor;
    private javax.swing.JLabel bntTurma;
    private javax.swing.JLabel bntUniversidade;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCINCUN;
    private javax.swing.JMenu mnAjuda;
    private javax.swing.JMenu mnSair;
    private javax.swing.JMenu mnSobre;
    private javax.swing.JMenuBar mnbLogin;
    private javax.swing.JMenuItem mntSair;
    // End of variables declaration//GEN-END:variables
}
