/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import java.awt.Color;

/**
 *
 * @author Jhonatan Borges
 */
public class PrincipalFinal extends javax.swing.JFrame {

    /**
     * Creates new form PrincipalFinal
     */
    public PrincipalFinal() {
        initComponents();
        setLocationRelativeTo(null);
        
        //bntCadastroAluno.setBackground(Color.yellow);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Logo = new javax.swing.JLabel();
        lblSlogan = new javax.swing.JLabel();
        bntAdicionarAluno = new javax.swing.JButton();
        bntAdicionarProfessor = new javax.swing.JButton();
        bntAdicionarUniversidade = new javax.swing.JButton();
        bntAdicionarTurma = new javax.swing.JButton();
        mnbLogin = new javax.swing.JMenuBar();
        mnAjuda = new javax.swing.JMenu();
        mnSobre = new javax.swing.JMenu();
        mnSair = new javax.swing.JMenu();
        mntSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/CyberTop.png"))); // NOI18N
        getContentPane().add(Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 33, 530, 76));

        lblSlogan.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblSlogan.setText("Aqui você garante sua aprovação");
        getContentPane().add(lblSlogan, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, -1, -1));

        bntAdicionarAluno.setBackground(new java.awt.Color(255, 102, 0));
        bntAdicionarAluno.setText("Adicionar Aluno");
        bntAdicionarAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntAdicionarAlunoActionPerformed(evt);
            }
        });
        getContentPane().add(bntAdicionarAluno, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 130, 60));

        bntAdicionarProfessor.setBackground(new java.awt.Color(255, 153, 0));
        bntAdicionarProfessor.setText("Adcionionar Professor");
        getContentPane().add(bntAdicionarProfessor, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, -1, 60));

        bntAdicionarUniversidade.setBackground(new java.awt.Color(255, 153, 51));
        bntAdicionarUniversidade.setText("Adicionar Universidade");
        getContentPane().add(bntAdicionarUniversidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 200, -1, 60));

        bntAdicionarTurma.setBackground(new java.awt.Color(255, 204, 0));
        bntAdicionarTurma.setText("Adicionar Turma");
        bntAdicionarTurma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntAdicionarTurmaActionPerformed(evt);
            }
        });
        getContentPane().add(bntAdicionarTurma, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 200, 120, 60));

        mnAjuda.setText("Ajuda");
        mnbLogin.add(mnAjuda);

        mnSobre.setText("Sobre");
        mnbLogin.add(mnSobre);

        mnSair.setText("Sair");
        mnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnSairActionPerformed(evt);
            }
        });

        mntSair.setText("Desejo realmente sair!");
        mntSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mntSairActionPerformed(evt);
            }
        });
        mnSair.add(mntSair);

        mnbLogin.add(mnSair);

        setJMenuBar(mnbLogin);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mntSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mntSairActionPerformed
        // Encerra a execução
        System.exit(0);
    }//GEN-LAST:event_mntSairActionPerformed

    private void mnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnSairActionPerformed

    }//GEN-LAST:event_mnSairActionPerformed

    private void bntAdicionarAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntAdicionarAlunoActionPerformed
        // TODO add your handling code here:
        CadastroAluno telaCadastroAluno = new CadastroAluno();
        telaCadastroAluno.setVisible(true);
    }//GEN-LAST:event_bntAdicionarAlunoActionPerformed

    private void bntAdicionarTurmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntAdicionarTurmaActionPerformed
        // TODO add your handling code here:
        new CadastroTurma().setVisible(true);
    }//GEN-LAST:event_bntAdicionarTurmaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalFinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalFinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalFinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalFinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrincipalFinal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Logo;
    private javax.swing.JButton bntAdicionarAluno;
    private javax.swing.JButton bntAdicionarProfessor;
    private javax.swing.JButton bntAdicionarTurma;
    private javax.swing.JButton bntAdicionarUniversidade;
    private javax.swing.JLabel lblSlogan;
    private javax.swing.JMenu mnAjuda;
    private javax.swing.JMenu mnSair;
    private javax.swing.JMenu mnSobre;
    private javax.swing.JMenuBar mnbLogin;
    private javax.swing.JMenuItem mntSair;
    // End of variables declaration//GEN-END:variables
}
