/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import java.awt.Color;
import java.io.IOException;
import java.net.URISyntaxException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Jhonatan Borges
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form PrincipalFinal
     */
    public Principal() {
        initComponents();
        setLocationRelativeTo(null);
        
        bntAlunoAdicionar.setVisible(false);
        bntUniversidadeAdicionar.setVisible(false);
        bntProfessorAdicionar.setVisible(false);
        bntTurmaAdicionar.setVisible(false);
        
        bntAlunoRemover.setVisible(false);
        bntUniversidadeRemover.setVisible(false);
        bntTurmaRemover.setVisible(false);
        
        //bntCadastroAluno.setBackground(Color.yellow);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LOGO = new javax.swing.JLabel();
        lblCINCUN = new javax.swing.JLabel();
        bntRemover = new javax.swing.JLabel();
        bntBuscar = new javax.swing.JLabel();
        bntAdicionar = new javax.swing.JLabel();
        bntAlunoAdicionar = new javax.swing.JLabel();
        bntUniversidadeAdicionar = new javax.swing.JLabel();
        bntProfessorAdicionar = new javax.swing.JLabel();
        bntTurmaAdicionar = new javax.swing.JLabel();
        bntAlunoRemover = new javax.swing.JLabel();
        bntUniversidadeRemover = new javax.swing.JLabel();
        bntTurmaRemover = new javax.swing.JLabel();
        background = new javax.swing.JLabel();
        mnbLogin = new javax.swing.JMenuBar();
        mnAjuda = new javax.swing.JMenu();
        mnSobre = new javax.swing.JMenu();
        mnSair = new javax.swing.JMenu();
        mntSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LOGO.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        LOGO.setForeground(new java.awt.Color(255, 255, 255));
        LOGO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/LOGO.jpg"))); // NOI18N
        LOGO.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LOGOMouseClicked(evt);
            }
        });
        getContentPane().add(LOGO, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, -1, 100));

        lblCINCUN.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 14)); // NOI18N
        lblCINCUN.setForeground(new java.awt.Color(255, 255, 255));
        lblCINCUN.setText("  Aqui você garante sua aprovação");
        getContentPane().add(lblCINCUN, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, 240, 30));

        bntRemover.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        bntRemover.setForeground(new java.awt.Color(255, 255, 255));
        bntRemover.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/eraser.png"))); // NOI18N
        bntRemover.setText("Remover");
        bntRemover.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bntRemoverMouseClicked(evt);
            }
        });
        getContentPane().add(bntRemover, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, -1, -1));

        bntBuscar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        bntBuscar.setForeground(new java.awt.Color(255, 255, 255));
        bntBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/buscar.png"))); // NOI18N
        bntBuscar.setText("Buscar");
        bntBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bntBuscarMouseClicked(evt);
            }
        });
        getContentPane().add(bntBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 150, -1, -1));

        bntAdicionar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        bntAdicionar.setForeground(new java.awt.Color(255, 255, 255));
        bntAdicionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/adicionar.png"))); // NOI18N
        bntAdicionar.setText("Adicionar");
        bntAdicionar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bntAdicionarMouseClicked(evt);
            }
        });
        getContentPane().add(bntAdicionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 150, -1, -1));

        bntAlunoAdicionar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        bntAlunoAdicionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/student.png"))); // NOI18N
        bntAlunoAdicionar.setText("Aluno");
        bntAlunoAdicionar.setToolTipText("Adicionar aluno");
        bntAlunoAdicionar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bntAlunoAdicionarMouseClicked(evt);
            }
        });
        getContentPane().add(bntAlunoAdicionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, -1, -1));

        bntUniversidadeAdicionar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        bntUniversidadeAdicionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/school.png"))); // NOI18N
        bntUniversidadeAdicionar.setText("Universidade");
        bntUniversidadeAdicionar.setToolTipText("Adicionar universidade");
        bntUniversidadeAdicionar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bntUniversidadeAdicionarMouseClicked(evt);
            }
        });
        getContentPane().add(bntUniversidadeAdicionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 320, -1, -1));

        bntProfessorAdicionar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        bntProfessorAdicionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/teacher.png"))); // NOI18N
        bntProfessorAdicionar.setText("Professor");
        bntProfessorAdicionar.setToolTipText("Adicionar professor");
        bntProfessorAdicionar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bntProfessorAdicionarMouseClicked(evt);
            }
        });
        getContentPane().add(bntProfessorAdicionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 250, -1, -1));

        bntTurmaAdicionar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        bntTurmaAdicionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/classroom.png"))); // NOI18N
        bntTurmaAdicionar.setText("Turma");
        bntTurmaAdicionar.setToolTipText("Adicionar turma");
        bntTurmaAdicionar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bntTurmaAdicionarMouseClicked(evt);
            }
        });
        getContentPane().add(bntTurmaAdicionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 320, -1, -1));

        bntAlunoRemover.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        bntAlunoRemover.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/student.png"))); // NOI18N
        bntAlunoRemover.setText("Aluno");
        bntAlunoRemover.setToolTipText("Remover aluno");
        getContentPane().add(bntAlunoRemover, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, -1, -1));

        bntUniversidadeRemover.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        bntUniversidadeRemover.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/school.png"))); // NOI18N
        bntUniversidadeRemover.setText("Universidade");
        bntUniversidadeRemover.setToolTipText("Remover universidade");
        getContentPane().add(bntUniversidadeRemover, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 320, -1, -1));

        bntTurmaRemover.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        bntTurmaRemover.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/classroom.png"))); // NOI18N
        bntTurmaRemover.setText("Turma");
        bntTurmaRemover.setToolTipText("Remover turma");
        getContentPane().add(bntTurmaRemover, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 320, -1, -1));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/grey.png"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 410));

        mnAjuda.setText("Ajuda");
        mnAjuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnAjudaActionPerformed(evt);
            }
        });
        mnbLogin.add(mnAjuda);

        mnSobre.setText("Sobre");
        mnbLogin.add(mnSobre);

        mnSair.setText("Sair");
        mnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnSairActionPerformed(evt);
            }
        });

        mntSair.setText("Desejo realmente sair!");
        mntSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mntSairActionPerformed(evt);
            }
        });
        mnSair.add(mntSair);

        mnbLogin.add(mnSair);

        setJMenuBar(mnbLogin);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mntSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mntSairActionPerformed
        // Encerra a execução
        System.exit(0);
    }//GEN-LAST:event_mntSairActionPerformed

    private void mnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnSairActionPerformed

    }//GEN-LAST:event_mnSairActionPerformed

    private void mnAjudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnAjudaActionPerformed
        try {
            // TODO add your handling code here:

            java.awt.Desktop.getDesktop().browse( new java.net.URI( "http://www.google.com" ) );
        } catch (URISyntaxException | IOException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_mnAjudaActionPerformed

    private void bntBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bntBuscarMouseClicked
        // TODO add your handling code here:
        bntRemover.setEnabled(false);
        bntBuscar.setEnabled(true);
        bntAdicionar.setEnabled(false);
        
        
        
    }//GEN-LAST:event_bntBuscarMouseClicked

    private void bntRemoverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bntRemoverMouseClicked
        // TODO add your handling code here:
        bntRemover.setEnabled(true);
        bntBuscar.setEnabled(false);
        bntAdicionar.setEnabled(false);
        
        bntAlunoAdicionar.setVisible(false);
        bntUniversidadeAdicionar.setVisible(false);
        bntProfessorAdicionar.setVisible(false);
        bntTurmaAdicionar.setVisible(false);
        
        bntAlunoRemover.setVisible(true);
        bntUniversidadeRemover.setVisible(true);
        //bntProfessorRemover.setVisible(false);
        bntTurmaRemover.setVisible(true);
        
        
        
    }//GEN-LAST:event_bntRemoverMouseClicked

    private void bntAdicionarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bntAdicionarMouseClicked
        // TODO add your handling code here:
        bntAdicionar.setEnabled(true);
        bntBuscar.setEnabled(false);
        bntRemover.setEnabled(false);
        
        bntAlunoAdicionar.setVisible(true);
        bntUniversidadeAdicionar.setVisible(true);
        bntProfessorAdicionar.setVisible(true);
        bntTurmaAdicionar.setVisible(true);
        
        
    }//GEN-LAST:event_bntAdicionarMouseClicked

    private void LOGOMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LOGOMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_LOGOMouseClicked

    private void bntAlunoAdicionarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bntAlunoAdicionarMouseClicked
        // TODO add your handling code here:
        
        new CadastroAluno().setVisible(true);
    }//GEN-LAST:event_bntAlunoAdicionarMouseClicked

    private void bntProfessorAdicionarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bntProfessorAdicionarMouseClicked
        // TODO add your handling code here:
        new CadastroProfessor().setVisible(true);
    }//GEN-LAST:event_bntProfessorAdicionarMouseClicked

    private void bntUniversidadeAdicionarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bntUniversidadeAdicionarMouseClicked
        // TODO add your handling code here:
        new CadastroUniversidade().setVisible(true);
    }//GEN-LAST:event_bntUniversidadeAdicionarMouseClicked

    private void bntTurmaAdicionarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bntTurmaAdicionarMouseClicked
        // TODO add your handling code here:
        new CadastroTurma().setVisible(true);
    }//GEN-LAST:event_bntTurmaAdicionarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LOGO;
    private javax.swing.JLabel background;
    private javax.swing.JLabel bntAdicionar;
    private javax.swing.JLabel bntAlunoAdicionar;
    private javax.swing.JLabel bntAlunoRemover;
    private javax.swing.JLabel bntBuscar;
    private javax.swing.JLabel bntProfessorAdicionar;
    private javax.swing.JLabel bntRemover;
    private javax.swing.JLabel bntTurmaAdicionar;
    private javax.swing.JLabel bntTurmaRemover;
    private javax.swing.JLabel bntUniversidadeAdicionar;
    private javax.swing.JLabel bntUniversidadeRemover;
    private javax.swing.JLabel lblCINCUN;
    private javax.swing.JMenu mnAjuda;
    private javax.swing.JMenu mnSair;
    private javax.swing.JMenu mnSobre;
    private javax.swing.JMenuBar mnbLogin;
    private javax.swing.JMenuItem mntSair;
    // End of variables declaration//GEN-END:variables
}
